### PR TITLE
Update URLs to cisagov

### PR DESCRIPTION
**Pull request by hillaryj**
Update URLs for move to `cisagov` org and remove unnecessary oauth url

## 🗣 Description

- Updates target URL for the move to the `cisagov` org
- Removes oauth from URL query to retrieve tarball since it's now a public repo

## 💭 Motivation and Context

Associated with https://github.com/cisagov/ansible-role-cyhy-core/issues/10 - removes deprecated oauth usage both due to deprecation as well as now the target is publicly accessible without an auth token.

## 🚥 Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by dav3r — COMMENTED** [review]
`ncats-webui` is still in a private repo, so this PR should be shelved until that changes.

**Comment by jsf9k** [comment]
> `ncats-webui` is still in a private repo, so this PR should be shelved until that changes.

Not shelved but repurposed!  We can still:
* Modernize this repo by pulling in upstream changes
* Change the Ansible code so that it no longer passes the OAuth token as a query parameter.  (See cisagov/ansible-role-cyhy-commander@12b352fbb41346b252b9763e5425561881584445 for an example of this.)

**Comment by jsf9k** [comment]
> Not shelved but repurposed!

Meh...maybe a new PR is better.  I repurposed cisagov/ansible-role-cyhy-commander#8, but that's pretty tacky and leaves some extra commits in the history.

**Review by jsf9k — CHANGES_REQUESTED** [review]
*Once #7 is merged into develop and pulled into this PR*, you still need to:
* Remove `defaults/main.yml`.
* Run `terraform destroy` in the `terraform` directory.
* Remove the `terraform` directory altogether.

**Review by jsf9k — APPROVED** [review]
Much simpler!

**Review by mcdonnnj — APPROVED** [review]
Looking fresh ✨

**Pull request merged**
